apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:   # Ensure this matches the pod's label selector
      app: web-app
  template:
    metadata:
      labels:
        app: web-app  # Label should match with the 'selector'
    spec:
      containers:
      - name: web
        #image: nginx
        image: jenkins/jenkins:lts  # Added `:lts` to use the Jenkins LTS image (optional)
        ports:
        - containerPort: 8080  # This should match the `targetPort` in the Service YAML
