apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: web-svc
spec:
  selectors:
    matchLabels:
      app: web-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
