apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: web-svc
spec:
  selector:  # Correct singular 'selector' field
    app: web-app  # This label must match the label in the Deployment pods
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080  # This should match the containerPort in the Deployment
    protocol: TCP
