apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins  # Ensure this matches the label of your Jenkins pod
  ports:
    - protocol: TCP
      port: 8080      # Port that Jenkins listens on inside the container
      targetPort: 8080 # Port inside the container
      nodePort: 30001  # NodePort assigned for external access
  type: NodePort      # Exposes the service externally via a NodePort
